name: build box64
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - box64/**
jobs:
  push:
    name: "yolks:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - box64
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v0.8.2"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.aliyun_owner }}
          password: ${{ secrets.aliyun_registry_token }}
      - uses: docker/login-action@v2
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.qcloud_owner }}
          password: ${{ secrets.qcloud_registry_token }}
      - uses: docker/build-push-action@v3
        with:
          context: ./box64
          file: ./${{ matrix.tag }}/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            registry.cn-hangzhou.aliyuncs.com/jiongzu/yolks:${{ matrix.tag }}
            ccr.ccs.tencentyun.com/jiongzu/yolks:${{ matrix.tag }}
